version: 2
jobs:
  start:
    docker:
      - image: debian:stretch
    steps:
      - run:
          name: Date start
          command: date
  validate_publiccode:
    docker: 
      - image: golang 
    steps:
      - checkout
      - run:
          name: Validate publiccode.yml
          #command: pwd ; ls -l 
          command: go get github.com/italia/publiccode-parser-go/pcvalidate; /go/bin/pcvalidate publiccode.yml
  end:
    docker:
      - image: debian:stretch
    steps:
      - run:
          name: Date end
          command: date

workflows:
  version: 2
  my_workflow:
    jobs:
      - start
      - validate_publiccode
      - end:
          requires:
            - start
