# IMPORTAT GUIDES:
#  - https://circleci.com/blog/using-circleci-workflows-to-replicate-docker-hub-automated-builds/
#  - https://circleci.com/docs/2.0/configuration-reference/#tags
#  - https://circleci.com/docs/2.0/workflows/#executing-workflows-for-a-git-tag
version: 2.1
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: ingv/fdsnws-fetcher
    docker:
      - image: circleci/buildpack-deps:stretch
jobs:
  start:
    docker:
      - image: debian:stretch
    steps:
      - run:
          name: Date start
          command: date
  build:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build docker image
          command: |
            IMAGE_TAG=${CIRCLE_TAG/v/''}
            docker build --no-cache --pull --tag $IMAGE_NAME:latest .
      - run:
          name: Archive Docker image
          command: |
            docker save -o image.tar $IMAGE_NAME
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
  publish-tag-and-latest:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo $DOCKERHUB_ACCESS_TOKEN | docker login -u $DOCKERHUB_USERNAME --password-stdin
            IMAGE_TAG=${CIRCLE_TAG/v/''}
            docker tag $IMAGE_NAME:latest $IMAGE_NAME:$IMAGE_TAG
            docker images
            docker push $IMAGE_NAME:latest
            docker push $IMAGE_NAME:$IMAGE_TAG
  end:
    docker:
      - image: debian:stretch
    steps:
      - run:
          name: Date end
          command: date

  test_publiccode:
    docker:
      - image: docker:18.06.0-ce
    steps:
      - checkout
      - setup_remote_docker
      - run:
          # https://github.com/italia/publiccode-parser-go
          name: Validate publiccode file
          command: |
            ### CircleCI cannot mount folder: https://circleci.com/docs/2.0/building-docker-images/#mounting-folders
            # create a dummy container which will hold a volume with config
            docker create -v /publiccode_folder --name myfolder alpine:3.4 /bin/true
            # copy a config file into this volume
            docker cp publiccode.yml myfolder:/publiccode_folder
            # start an application container using this volume
            docker run --rm --volumes-from myfolder italia/publiccode-parser-go publiccode_folder/publiccode.yml

workflows:
  version: 2.1
  fdsnws-fetcher-workflow:
    jobs:
      - start:
          filters:
            tags: # If neither only nor ignore are specified then the job is skipped for all tags: https://circleci.com/docs/2.0/configuration-reference/#tags
              only: /^v.*/
      - build:
          requires:
            - start
          filters:
            tags: # If neither only nor ignore are specified then the job is skipped for all tags: https://circleci.com/docs/2.0/configuration-reference/#tags
              only: /^v.*/
            branches:
              ignore: /.*/
      - test_publiccode:
          requires:
            - start            
          filters:
            tags:
              only: /^v.*/
      - publish-tag-and-latest:
          context:
            - valentino
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - end:
          requires:
            - publish-tag-and-latest 
          filters:
            tags:
              only: /^v.*/
