version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date
      - run:
          name: test path
          command: |
            pwd
            ls -l
  validate_publiccode:
    docker: 
      - image: golang 
    steps:
      - checkout
      - run:
          name: Validate publiccode.yml
          #command: pwd ; ls -l 
          command: go get github.com/italia/publiccode-parser-go/pcvalidate; /go/bin/pcvalidate publiccode.yml

workflows:
  version: 2
  my_workflow:
    jobs:
      - build
      - validate_publiccode:
          requires:
            - build
